import React from 'react'

type Step = {
  key: string
  label: string
  icon: string
  description: string
}

const STEPS: Step[] = [
  { key: 'pending_coding',   label: 'Documented',      icon: '📋', description: 'Encounter documented by doctor' },
  { key: 'coded',            label: 'Coded',            icon: '🏷️', description: 'ICD-10 & CPT codes assigned' },
  { key: 'sent_to_biller',   label: 'Invoiced',         icon: '🧾', description: 'Invoice generated by biller' },
  { key: 'claim_submitted',  label: 'Claim Submitted',  icon: '📤', description: 'Submitted to clearinghouse' },
  { key: 'approved',         label: 'Approved',         icon: '✅', description: 'Payer approved the claim' },
  { key: 'paid',             label: 'Paid',             icon: '💰', description: 'Payment posted' },
]

const DENIED_STEP: Step = { key: 'denied', label: 'Denied', icon: '❌', description: 'Payer denied the claim' }

interface ClaimTimelineProps {
  encounterStatus: string
  claimStatus?: string
  claimNumber?: string
  denialReason?: string
  compact?: boolean
}

const getActiveIndex = (encStatus: string, claimStatus?: string): number => {
  if (claimStatus === 'paid') return 5
  if (claimStatus === 'approved') return 4
  if (claimStatus === 'denied') return -1 // special
  if (encStatus === 'claim_submitted' || claimStatus === 'submitted') return 3
  if (encStatus === 'sent_to_biller') return 2
  if (encStatus === 'coded') return 1
  return 0
}

export const ClaimTimeline: React.FC<ClaimTimelineProps> = ({
  encounterStatus, claimStatus, claimNumber, denialReason, compact = false
}) => {
  const isDenied = claimStatus === 'denied'
  const activeIdx = getActiveIndex(encounterStatus, claimStatus)
  const steps = isDenied ? [...STEPS.slice(0, 4), DENIED_STEP] : STEPS

  return (
    <div className={`w-full ${compact ? 'py-2' : 'py-4'}`}>
      {claimNumber && (
        <p className="text-xs text-gray-500 dark:text-gray-400 mb-3">
          Claim <span className="font-mono font-semibold text-blue-600 dark:text-blue-400">{claimNumber}</span>
        </p>
      )}
      <div className="relative">
        {/* Progress Line */}
        <div className="absolute top-5 left-5 right-5 h-0.5 bg-gray-200 dark:bg-gray-700 z-0">
          <div
            className="h-full bg-gradient-to-r from-blue-500 to-blue-600 transition-all duration-700"
            style={{ width: isDenied ? '66%' : `${(activeIdx / (steps.length - 1)) * 100}%` }}
          />
        </div>

        <div className={`relative z-10 flex ${compact ? 'justify-between' : 'justify-between gap-1'}`}>
          {steps.map((step, idx) => {
            const isCompleted = isDenied ? idx < 3 : idx <= activeIdx
            const isCurrent = isDenied ? idx === 4 : idx === activeIdx
            const isDeniedStep = step.key === 'denied'

            return (
              <div key={step.key} className="flex flex-col items-center flex-1 min-w-0">
                {/* Circle */}
                <div className={`
                  w-10 h-10 rounded-full flex items-center justify-center text-base
                  border-2 transition-all duration-300 flex-shrink-0
                  ${isDeniedStep && isCurrent
                    ? 'bg-red-100 border-red-500 dark:bg-red-900/30 dark:border-red-500 shadow-red-200 shadow-md'
                    : isCompleted
                    ? 'bg-blue-600 border-blue-600 shadow-md shadow-blue-200 dark:shadow-blue-900'
                    : 'bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600'
                  }
                `}>
                  {isCompleted && !isDeniedStep ? (
                    <span className="text-white text-xs font-bold">✓</span>
                  ) : (
                    <span className={`text-sm ${isCurrent && isDeniedStep ? '' : isCompleted ? 'text-white' : 'text-gray-400'}`}>
                      {step.icon}
                    </span>
                  )}
                </div>

                {/* Label */}
                {!compact && (
                  <div className="mt-2 text-center px-1">
                    <p className={`text-xs font-semibold leading-tight ${
                      isCurrent && isDeniedStep ? 'text-red-600 dark:text-red-400' :
                      isCompleted ? 'text-blue-700 dark:text-blue-400' : 'text-gray-400 dark:text-gray-500'
                    }`}>
                      {step.label}
                    </p>
                    <p className="text-[10px] text-gray-400 dark:text-gray-500 leading-tight hidden sm:block mt-0.5">
                      {step.description}
                    </p>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      </div>

      {isDenied && denialReason && (
        <div className="mt-3 p-2 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800">
          <p className="text-xs text-red-700 dark:text-red-300">
            <span className="font-semibold">Denial Reason:</span> {denialReason}
          </p>
        </div>
      )}
    </div>
  )
}

export default ClaimTimeline
