"""add_npi_cms1500_auditlog_claim_improvements

Revision ID: 9642b0229648
Revises: 50d82fafc276
Create Date: 2026-03-08 12:32:03.355362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9642b0229648'
down_revision: Union[str, Sequence[str], None] = '50d82fafc276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('claim_type', sa.String(), nullable=True))
    op.add_column('claims', sa.Column('billing_provider_npi', sa.String(length=10), nullable=True))
    op.add_column('claims', sa.Column('rendering_provider_npi', sa.String(length=10), nullable=True))
    op.add_column('claims', sa.Column('denial_reason_code', sa.String(length=10), nullable=True))
    op.add_column('claims', sa.Column('adjudication_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('claims', sa.Column('payer_control_number', sa.String(), nullable=True))
    op.add_column('claims', sa.Column('cms1500_data', sa.JSON(), nullable=True))
    op.add_column('clinical_encounters', sa.Column('place_of_service_code', sa.String(length=2), nullable=True))
    op.add_column('clinical_encounters', sa.Column('referring_provider_npi', sa.String(length=10), nullable=True))
    op.add_column('clinical_encounters', sa.Column('facility_npi', sa.String(length=10), nullable=True))
    op.add_column('invoices', sa.Column('adjustment_amount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('medical_codes', sa.Column('modifier_1', sa.String(length=2), nullable=True))
    op.add_column('medical_codes', sa.Column('modifier_2', sa.String(length=2), nullable=True))
    op.add_column('medical_codes', sa.Column('units', sa.Integer(), nullable=True, server_default='1'))
    op.add_column('medical_codes', sa.Column('charge_amount', sa.Float(), nullable=True))
    op.add_column('medical_codes', sa.Column('diagnosis_pointers', sa.String(length=8), nullable=True))
    op.add_column('medical_codes', sa.Column('place_of_service_code', sa.String(length=2), nullable=True))
    op.add_column('payments', sa.Column('payer_type', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('check_number', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('posting_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('npi_number', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('taxonomy_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('license_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('license_state', sa.String(length=2), nullable=True))
    # NOTE: op.alter_column is a no-op for SQLite (columns already have correct nullable/defaults)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'license_state')
    op.drop_column('users', 'license_number')
    op.drop_column('users', 'taxonomy_code')
    op.drop_column('users', 'npi_number')
    op.drop_column('payments', 'posting_date')
    op.drop_column('payments', 'check_number')
    op.drop_column('payments', 'payer_type')
    op.drop_column('medical_codes', 'place_of_service_code')
    op.drop_column('medical_codes', 'diagnosis_pointers')
    op.drop_column('medical_codes', 'charge_amount')
    op.drop_column('medical_codes', 'units')
    op.drop_column('medical_codes', 'modifier_2')
    op.drop_column('medical_codes', 'modifier_1')
    op.drop_column('invoices', 'notes')
    op.drop_column('invoices', 'adjustment_amount')
    op.drop_column('clinical_encounters', 'facility_npi')
    op.drop_column('clinical_encounters', 'referring_provider_npi')
    op.drop_column('clinical_encounters', 'place_of_service_code')
    op.drop_column('claims', 'cms1500_data')
    op.drop_column('claims', 'payer_control_number')
    op.drop_column('claims', 'adjudication_date')
    op.drop_column('claims', 'denial_reason_code')
    op.drop_column('claims', 'rendering_provider_npi')
    op.drop_column('claims', 'billing_provider_npi')
    op.drop_column('claims', 'claim_type')
    # ### end Alembic commands ###
